export const types = {
  LOGGIN: "[AUTH] LOGGIN",
  LOGOUT: "[AUTH] LOGOUT",

  UISETERROR: "[UI] UISETERROR",
  UIREMOVEERROR: "[UI] UIREMOVEERROR",
  UISETLOADING: "[UI] UISETLOADING",
  UIREMOVELOADING: "[UI] UIREMOVELOADING",

  ADDNOTES: "[NOTES] ADDNOTES",
  SETNOTES: "[NOTES] SETNOTES",
  REMOVENOTES: "[NOTES] REMOVENOTES",
  UPDATENOTES: "[NOTES] UPDATENOTES",
  LOADNOTES: "[NOTES] LOADNOTES",
  ACTIVENOTE: "[NOTES] ACTIVENOTE",
  NOTESUPLOAD: "[NOTES] NOTESUPLOAD",
  NOTESFILEURL: "[NOTES] NOTESFILEURL",
  NOTESLOGOUTCLEANER: "[NOTES] NOTESLOGOUTCLEANER",
  NEWADDNOTES: "[NOTES] NEWADDNOTES",
};
